### PR TITLE
Add performance notebooks

### PR DESCRIPTION
**Pull request by rabernat**
This PR adds a few notebooks that I am using to assess performance of Icechunk vs Zarr 2 and Zarr 3. These have to be in separate notebooks because they use different environments.

Not planning to publish or publicize these very obviously, but I want to have them on file to back up some of the plots I'm going to share.

### CODE REVIEW

**Comment by rsignell** [comment]
Does the ERA5 notebook require this xarray PR? https://github.com/TomAugspurger/xarray/tree/fix/zarr-v3

**Comment by mpiannucci** [comment]
> Does the ERA5 notebook require this xarray PR? https://github.com/TomAugspurger/xarray/tree/fix/zarr-v3

Yes, all zarr 3 usage needs that PR at this time

**Comment by rsignell** [comment]
@mpiannucci cool.  Is there a environment.yml handy to run that era5 notebook?

**Comment by rabernat** [comment]
@rsignell - would love to see if you can replicate our results! We're super psyched about the performance we've seen from Icechunk so far.

**Comment by jhamman** [comment]
@rsignell - here's a env file that should get you up and running (minus jupyter, etc.)

```yaml
name: icechunk
dependencies:
  - numpy
  - xarray
  - h5netcdf
  - dask
  - fsspec
  - numcodecs
  - pip
  - pip:
    - icechunk
    - git+https://github.com/pydata/xarray@zarr-v3
```

**Pull request merged**
